### ISSUE TITLE
What is the license for this script?

### ISSUE THREAD

**Issue by palopezv** [benapetr/compress#1]
@benapetr I want to package this script for the Arch Linux User Repository, but I need to know the licensing terms. If you don't explicitly state the license you are publshing a propietary work under copyright law, which is enforceable everywhere under the 1886 Berne Convention and all the treaties signed under the World Trade Organization since the creation of the UN, even if the work is yours. See [1] for a short description of the problem.

If you want to dedicate it to the public domain, it becomes a rather thorny issue, because the public domain does not exist in many countries due to legislation stating that copyright law is above the will of the individual renouncing his/her rights. If that is the case, may I suggest you use the "unlicense"[2]? That's what I use to dedicate my little works to the public domain.

[1] http://choosealicense.com/no-license/
[2] http://unlicense.org/

**Comment by benapetr** [comment]
Hi,
I have no problem releasing with no license, although I usually use GPLv3 or LGPL, but the website you sent me doesn't seem to work? http://unlicense.org/ Server not found

**Comment by benapetr** [comment]
I couldn't find much about unlicense, so it's now licensed with BSD, which I find more permissive than GPL

**Comment by palopezv** [comment]
Thank you very much. You are right. Apparently the owner of the web site let it lapse, as recently as the beginnng of this month. Here is the link to the last entry in archive.org, for completeness sake:

https://web.archive.org/web/20170630121319/http://unlicense.org/
